name: Fetch Portals

on:
  push:
    branches:
      - master

jobs:
  Portals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup ssh keys
        uses: webfactory/ssh-agent@v0.2.0
        with:
            ssh-private-key: ${{ secrets.PORTAL_DEPLOY_KEY }}

      - name: Combine and fetch portals
        run: |
          sudo apt install python
          python combine.py